CI

diff --git a/.github/workflows/ansible_test.yml b/.github/workflows/ansible_test.yml
--- a/.github/workflows/ansible_test.yml
+++ b/.github/workflows/ansible_test.yml
@@ -58,9 +58,8 @@ jobs:
       - name: Real Ansible run
         run: ansible-playbook -i tests/inventory tests/test.yml
 
-      - name: Second run to check for indempotence (allow 2 'changes' for staus checks)
-        run: "ansible-playbook -i tests/inventory tests/test.yml"
-        # | grep -q 'changed=2.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
+      - name: Second run to check for indempotence (allow 4 'changes' for staus checks)
+        run: "ansible-playbook -i tests/inventory tests/test.yml | grep -q 'changed=4.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
 
       - name: Setup serverspec (install gem)
         run: sudo gem install serverspec
@@ -68,7 +67,7 @@ jobs:
       - name: Wait until Graylog is reachable and show log output to verify
         run: |
           sleep 15
-          tail -n 10 /var/log/graylog-server/server.log
+#          tail -n 10 /var/log/graylog-server/server.log
 
       - name: Curl Graylog http endpoint
         run: curl --silent http://localhost:9000/api/
